name: Deploy to AKS Cluster
#on: [push]
on:
  push:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Install Dependencies for the app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/checkout@master
    
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - run: |
        docker build . -t vivek4sinha/multi:${{ github.sha }}
        docker push vivek4sinha/multi:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: airflow
        resource-group: demo

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          manifests/deployment.yaml=vivek4sinha/multi:${{ github.sha }}
