name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HELM_RELEASE_NAME: "airflow"
  HELM_CHART_REPO: "https://airflow.apache.org"
  HELM_CHART_NAME: "apache-airflow/airflow"
  NAMESPACE: "airflow"
  DOCKER_URL: "https://hub.docker.com/"
  ENVIRONMENT: "stage"


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: 'vivek4sinha/airflow-docker:1234'
