name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HELM_RELEASE_NAME: "airflow"
  HELM_CHART_REPO: "https://airflow.apache.org"
  HELM_CHART_NAME: "apache-airflow/airflow"
  NAMESPACE: "airflow"
  DOCKER_URL: "https://hub.docker.com/"
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ENVIRONMENT: "stage"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to private registry
      uses: docker/login-action@v1
      with:
        registry: DOCKER_URL
        username: DOCKER_USER
        password: DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag vivek4sinha/airflow-docker:0606
    - name: Docker Push
      run: docker push vivek4sinha/airflow-docker:0606
